// <auto-generated />
using System;
using AMHP.Avaliacao.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMHP.Avaliacao.Data.Migrations
{
    [DbContext(typeof(AvaliacaoContext))]
    partial class AvaliacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("AMHP.Avaliacao.Domain.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AMHP.Avaliacao.Domain.UsuarioPerguntaResposta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pergunta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resposta")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioPerguntaResposta");
                });

            modelBuilder.Entity("AMHP.Avaliacao.Domain.UsuarioPerguntaResposta", b =>
                {
                    b.HasOne("AMHP.Avaliacao.Domain.Usuario", null)
                        .WithMany("UsuarioPerguntaRespostas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AMHP.Avaliacao.Domain.Usuario", b =>
                {
                    b.Navigation("UsuarioPerguntaRespostas");
                });
#pragma warning restore 612, 618
        }
    }
}
